### ISSUE TITLE
Bug report in python code

### ISSUE THREAD

**Issue by bearsan** [wubaoyuan/Lpbox-ADMM#2]
There is a bug in column 49 of the code in https://github.com/wubaoyuan/Lpbox-ADMM/blob/master/python/functions/util.py.
It should be corrected as 
`spatial_indices = np.hstack((rmat.reshape(-1,1),cmat.reshape(-1,1)))`
And thank you for your paper and code!

**Comment by wubaoyuan** [comment]
@bearsan Greatly appreciated for indicating this typo. It has been corrected.
